name = "fortran-2048"
version = "0.1.0"
license = "license"
author = "lukbrb"
maintainer = "lucasbarbr@outlook.com"
copyright = "Copyright 2024, lukbrb"

[preprocess]
[preprocess.cpp]
macros=["FC={-fno-range-check}"]

[library]
include-dir = ["raylib-source/include/raylib.h"]
build-script = "set_variables.sh"

[[executable]]
name="fort-2048"
source-dir="app"
main="main.f90"
link = ["raylib"]