name = "fortran-2048"
version = "0.1.0"
license = "license"
author = "lukbrb"
maintainer = "lucasbarbr@outlook.com"
copyright = "Copyright 2024, lukbrb"

[build]
link = [ "OpenGL", "pthread", "m" ]



[library]
source-dir = "src"
"include-dir" = ["include"]