name = "fortran-2048"
version = "0.1.0"
license = "license"
author = "lukbrb"
maintainer = "lucasbarbr@outlook.com"
copyright = "Copyright 2024, lukbrb"

[library]
include-dir = ["raylib-5.0/include/"]
build-script = "././fpm_build.sh"

[build]
link=["raylib"]

[[executable]]
name="fort-2048"
source-dir="app"
main="main.f90"
